version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "GHA CI"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
