name: CI - macOS

on: [pull_request, push]

permissions:
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Build
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Install dependencies
        run: |
          brew update > /dev/null
          brew install cmake ninja
          brew install create-dmg

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.*"
          modules: qtimageformats qtmultimedia

      - name: Build application
        run: |
          cmake \
            -B build \
            -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build --target update_translations
          cmake --build build

      - name: Prepare build artifacts
        run: |
          pushd build/app
          rm DigitalClock5.app/Contents/PlugIns/sample.dylib
          macdeployqt DigitalClock5.app
          rm DigitalClock5.app/Contents/PlugIns/multimedia/libffmpegmediaplugin.dylib
          rm DigitalClock5.app/Contents/Frameworks/libav*
          rm DigitalClock5.app/Contents/Frameworks/libsw*
          macdeployqt DigitalClock5.app -no-plugins -codesign=-
          popd
          mkdir upload
          create-dmg --volname "Digital Clock 5" --window-size 400 300 --text-size 16 --icon-size 128 --icon "DigitalClock5.app" 30 110 --app-drop-link 200 110 --format UDBZ upload/digital_clock_5-macos.dmg build/app/DigitalClock5.app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DigitalClock5 macOS Nightly
          path: upload
