name: CI - macOS

on: [pull_request, push]

permissions:
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Build
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Install dependencies
        run: |
          brew update > /dev/null
          brew install cmake ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.7.*"
          archives: qtbase qtsvg
          modules: qtmultimedia

      - name: Build application
        run: |
          cmake \
            -B build \
            -G Ninja \
            -D CMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build

      - name: Prepare build artifacts
        run: |
          pushd build/app
          macdeployqt DigitalClock5.app
          macdeployqt DigitalClock5.app -dmg -codesign=-
          popd
          mkdir upload
          mv build/app/DigitalClock5.dmg upload/digital_clock_5-macos.dmg

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DigitalClock5 macOS Nightly
          path: upload
