name: CI-Coverity-Basic
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Coverity Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ vars.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
